### ISSUE TITLE
build-storybook?

### ISSUE THREAD

**Issue by zksailor534** [kadirahq/react-cdk#29]
In publish_storybook.sh, I find the following code:
`# run our compile script, discussed above`
`build-storybook -o .out`

I think it references a script or capability provided elsewhere (maybe @kadira/storybook-deployer?), but I can't find it anywhere in this project.  I'm attempting to implement this script cross platform (Windows), but I'm not sure where to go here.

**Comment by usulpro** [comment]
@zksailor534 
`build-storybook` is a part of React Storybook cli and you can find it in `node_modules\.bin\build-storybook.cmd` if you on Windows.
So if you only want to build your storybook you can run it manually. (make sure that you have `node_modules\.bin\` in your `path`). 
You cant run the whole script on Windows because it `shell` sript, but there are some ways to solve this:

1. If you use [cmder](http://cmder.net/) just run it as usual. It'll be executed via `bash` automatically

2. You can use [publish_storybook.cmd](https://github.com/sm-react/react-cdk-windows-scripts/blob/master/publish_storybook.cmd) - windows version of this script

3. You can use [shelljs](https://github.com/sm-react/react-theming#scripts) version of this script wich supports Windows as well
