### ISSUE TITLE
When can we implement Styled Component?

### ISSUE THREAD

**Issue by adamchenwei** [kadirahq/react-cdk#32]
https://github.com/styled-components/styled-components

**Comment by adamchenwei** [comment]
ref https://github.com/styled-components/styled-components

**Comment by adamchenwei** [comment]
like an option for scss or styled-component to be default style engine for the generated project?

**Comment by jbovenschen** [comment]
I don't know what you mean to get for certain. But from what I see is that you want to use some solution for styling? solutions like `styled-components`, `glamor`, `jss` and glamorous are just one `npm install` or `yarn add` away.  

In the case of scss or any other it is a little more complex because it will force us to use one of many sollutions, which can be added by overwriting the `.storybook/wepack.config.js` file.

**Comment by adamchenwei** [comment]
Gotcha thanks for the answer
